blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/attributeerror/AttributeCalloutPack/discussions
    about: Start a discussion if you've got a question, want to discuss a new feature, etc.